### PR TITLE
Support conflict-marker-size larger than 7

### PR DESCRIPTION
**Pull request by sybereal**
[`conflict-marker-size`](https://git-scm.com/docs/gitattributes#_conflict_marker_size) is an attribute that allows overriding the length of conflict markers generated by Git. This PR adjusts the default regex patterns to support that scenario.

### CODE REVIEW

**Review by rhysd — APPROVED** [review]

**Comment by rhysd** [comment]
Thanks. I didn't know this.

**Comment by sybereal** [comment]
What is the issue with matchit that this triggers? I have admittedly never tried using the jump feature.
Additionally, I am using https://github.com/andymass/vim-matchup instead of native matchit, and I don't know if that is affected by the same bug.

**Comment by rhysd** [comment]
The issue is that matchit.vim doesn't handle escaped `,` correctly in patterns. This change introduced `,` in pattern (e.g. `^>>>>>>>` to `^>\{7,}`) so it hit the issue.
I'll make an issue on vim/vim repository and link it to this. Note that 0e9686f is a temporary workaround for the issue. Once the issue is solved, I'll revert the revert commit again.

**Comment by sybereal** [comment]
Ah, I see. I can rewrite the expressions without `,` using `+` instead later, if that helps.

**Comment by rhysd** [comment]
Oh, that sounds a good idea I could not come up with. I'll try it.

**Comment by rhysd** [comment]
https://github.com/rhysd/conflict-marker.vim/commit/bdc226cca8cb19360bc8424f2ed78f48b07113dc

I applied the idea at the above commit. It is already committed to the main branch.

**Comment by sybereal** [comment]
Thank you for the swift response and resolution!

**Pull request merged**
